"""Data Sources.

Every connector here is a labelled simulator, never presented as a live feed.
Status is derived from how recently the connector actually produced data — a
demo run makes the sensor and SCADA connectors look 'Connected'; before the
first run they correctly show 'Disconnected'.
"""

from __future__ import annotations

import datetime as dt

from fastapi import APIRouter, Depends
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from ..db.models import SensorReading, WeatherReading
from .deps import get_db

router = APIRouter(prefix="/api/datasources", tags=["data-sources"])

STATIC_SOURCES = [
    {
        "id": "src-satellite",
        "name": "Satellite methane feed",
        "type": "Satellite (simulated)",
        "label": "DEMO CONNECTOR — SIMULATED",
        "data_quality": 0.0,
        "latency_s": None,
        "status": "Disconnected",
        "note": "Not wired into this prototype; shown for product completeness.",
    },
    {
        "id": "src-ldar",
        "name": "Historical LDAR records",
        "type": "Leak detection and repair archive",
        "label": "DEMO CONNECTOR — SIMULATED",
        "data_quality": 0.9,
        "latency_s": None,
        "status": "Connected",
        "note": "Seeded historical events act as the LDAR record for this demo.",
    },
    {
        "id": "src-maintenance",
        "name": "Maintenance records",
        "type": "CMMS extract (simulated)",
        "label": "DEMO CONNECTOR — SIMULATED",
        "data_quality": 0.95,
        "latency_s": None,
        "status": "Connected",
        "note": "Seeded maintenance history, including the overdue C-03 seal inspection.",
    },
    {
        "id": "src-gis",
        "name": "Facility GIS / layout",
        "type": "Plant layout (simulated)",
        "label": "DEMO CONNECTOR — SIMULATED",
        "data_quality": 1.0,
        "latency_s": None,
        "status": "Connected",
        "note": "Local plant-frame coordinates power the schematic; no full GIS.",
    },
]


def _recency_status(last_ts: dt.datetime | None, warn_s: float, fail_s: float) -> tuple[str, float | None]:
    if last_ts is None:
        return "Disconnected", None
    age = (dt.datetime.now(dt.timezone.utc) - last_ts).total_seconds()
    if age <= warn_s:
        return "Connected", round(age, 1)
    if age <= fail_s:
        return "Degraded", round(age, 1)
    return "Disconnected", round(age, 1)


@router.get("")
def list_sources(db: Session = Depends(get_db)):
    last_sensor = db.scalar(select(func.max(SensorReading.ts)))
    last_weather = db.scalar(select(func.max(WeatherReading.ts)))
    sensor_count = db.scalar(select(func.count(func.distinct(SensorReading.sensor_id)))) or 0

    sensor_status, sensor_latency = _recency_status(last_sensor, 300, 3600)
    weather_status, weather_latency = _recency_status(last_weather, 300, 3600)

    sources = [
        {
            "id": "src-ch4-sensors",
            "name": "Fixed CH4 sensors",
            "type": "Point methane sensors (simulated)",
            "label": "DEMO CONNECTOR — SIMULATED",
            "sensor_count": int(sensor_count),
            "last_packet": last_sensor.isoformat() if last_sensor else None,
            "last_sync": last_sensor.isoformat() if last_sensor else None,
            "latency_s": sensor_latency,
            "data_quality": 0.98,
            "status": sensor_status,
            "note": "Generated by the EMISSIQ sensor simulator, not live plant hardware.",
        },
        {
            "id": "src-weather",
            "name": "Weather station",
            "type": "Met mast (simulated)",
            "label": "DEMO CONNECTOR — SIMULATED",
            "last_packet": last_weather.isoformat() if last_weather else None,
            "last_sync": last_weather.isoformat() if last_weather else None,
            "latency_s": weather_latency,
            "data_quality": 0.97,
            "status": weather_status,
            "note": "Wind speed/direction/stability for the plume model.",
        },
        {
            "id": "src-scada",
            "name": "SCADA / equipment simulator",
            "type": "Process data (simulated)",
            "label": "DEMO CONNECTOR — SIMULATED",
            "last_packet": last_sensor.isoformat() if last_sensor else None,
            "last_sync": last_sensor.isoformat() if last_sensor else None,
            "latency_s": sensor_latency,
            "data_quality": 0.96,
            "status": sensor_status,
            "note": "Read-only: pressure, flow and equipment state. EMISSIQ never writes to SCADA.",
        },
        *STATIC_SOURCES,
    ]
    return sources
